
#define MOTORFA   REGISTER_BIT(PORTC,0)
#define MOTORFB   REGISTER_BIT(PORTC,1)
#define PWMF      OCR0

#define MOTORLA   REGISTER_BIT(PORTC,3)
#define MOTORLB   REGISTER_BIT(PORTC,2)
#define PWML      OCR1A

#define MOTORBA   REGISTER_BIT(PORTC,5)
#define MOTORBB   REGISTER_BIT(PORTC,4)
#define PWMB      OCR1B

#define MOTORRA   REGISTER_BIT(PORTC,7)
#define MOTORRB   REGISTER_BIT(PORTC,6)
#define PWMR      OCR1C

#define LMGA      REGISTER_BIT(PORTD,4)
#define LMGB      REGISTER_BIT(PORTD,5)
#define LMGBRAKE  REGISTER_BIT(PORTD,7)

#define BSUP      REGISTER_BIT(PIND,0) // IF CHANGING CHANGE INTERRUPT
#define BSDOWN    REGISTER_BIT(PIND,1)//VECTORS IN ISR

#define PISTON1A   REGISTER_BIT(PORTB,2)
#define PISTON1B   REGISTER_BIT(PORTB,3)

#define PISTON2A  REGISTER_BIT(PORTB,0)
#define PISTON2B  REGISTER_BIT(PORTB,1)